RedditClone/config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :subs do 
    resources :posts, only: [:new, :create]
  end

  resources :posts, only: [ :edit, :show, :destroy, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/post.rb
class Post < ApplicationRecord

    belongs_to :author, 
    primary_key: :id, 
    foreign_key: :author_id,
    class_name: :User 

    belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub 


    has_many :crossposts, 
        primary_key: :id, 
        foreign_key: :post_id, 
        class_name: :PostSub
end

RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord

    validates :post_id, :sub_id, presence: true

    belongs_to :post, 
    primary_key: :id,
    foreign_key: :post_id, 
    class_name: :Post 

    belongs_to :sub, 
    primary_key: :id,
    foreign_key: :sub_id, 
    class_name: :Sub 


end

RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, presence: true 

    belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User 

    has_many :posts,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Post

    
    
    has_many :crossposts, 
        primary_key: :id, 
        foreign_key: :sub_id, 
        class_name: :PostSub
 
end
    

RedditClone/app/models/user.rb
class User < ApplicationRecord 
    validates :username, :password_digest, presence: true 
    validates :password, length: { minimum: 6, allow_nil: true }

    has_many :subs, 
        primary_key: :id, 
        foreign_key: :user_id, 
        class_name: :Sub 

    has_many :posts, 
    primary_key: :id, 
    foreign_key: :author_id, 
    class_name: :Post

















    attr_reader :password 
    after_initialize :ensure_session_token
    def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)
    end

    def ensure_session_token 
        self.session_token ||= SecureRandom.base64
    end

    def reset_session_token! 
        self.session_token = SecureRandom.base64
        self.save! 
        self.session_token
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return user if user && user.is_password?(password)
        # return nil if user.nil? 
        # if user.is_password?(password)
        #     return user 
        # end 
        # return nil 
    end 
end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :logged_in?, :current_user, :logout
    def log_in!(user)
         session[:session_token] = user.reset_session_token!
         
    end

    def ensure_logged_in? 
        redirect_to new_session_url unless logged_in? 
    end

    def logged_in?
        !!current_user
    end
    
    def current_user 
        @current_user = User.find_by(session_token: session[:session_token])
    end

    def logout
        current_user.reset_session_token! 
        session[:session_token] = nil 
        @current_user = nil
    end

    def require_moderator
        redirect_to subs_url unless current_user.subs.ids.include?(params[:id].to_i)
    end
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def new
        @post = Post.new 
        render :new 
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id 
        @post.sub_id = params[:sub_id]
        if @post.save 
            
            params[:post][:sub_id].each do |sub_id| 
                PostSub.create!(post_id: @post.id , sub_id: sub_id)
            end 
            redirect_to sub_url(@post.sub)
        else 
            flash.now[:errors] = @post.errors.full_messages 
            render :new 
        end 
    end

   def show 
    @post = Post.find_by(id: params[:id])
    render :show 
   end 

   def edit
    @subs = Sub.all 
        @post = Post.find_by(id: params[:id])
        if @post.author == current_user
            render :edit 
        end 
    
   end 

   def update 
        @post = Post.find_by(id: params[:id])
        if @post.update(post_params)
            redirect_to sub_url(@post.sub)
        else 
            flash.now[:errors] = @post.errors.full_messages
            render :edit 
        end
   end

   def destroy 
        @post = Post.find_by(id: params[:id])
        if @post.author == current_user
            @post.destroy 
        else 
            redirect_to sub_url(@post.sub)
        end

   end 

    private

    def post_params
        params.require(:post).permit(:title, :url, :content)
    end

end

RedditClone/app/controllers/sessions_controller.rb

class SessionsController < ApplicationController 

    before_action :ensure_logged_in?, only: [:destroy]

    def new 
      debugger
        render :new 
    end 

    def create 
        
          @user =  User.find_by_credentials(params[:user][:username], params[:user][:password])
          if @user.nil?
            flash[:errors] = ["Invalid username or password"]
            render :new 
          else 
            log_in!(@user)
            redirect_to users_url
          end 
    end 

    def destroy 
        logout
        redirect_to new_session_url
    end
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController 
    before_action :require_moderator, only: [:edit]
    def new 
        @sub = Sub.new 
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.user_id = current_user.id
        if @sub.save
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages 
            render :new
        end 
    end

    def show 
        @subs = Sub.all
        @sub = Sub.find_by(id: params[:id])
        render :show
    end

    def index
        @subs = Sub.all 
        render :index
    end

    def destroy 
        @sub = Sub.find_by(id: params[:id])
        if @sub.is_moderator?(current_user)
            @sub.destroy 
        end
        redirect_to user_url(current_user)
    end
    

    def edit 
        @sub = Sub.find_by(id: params[:id] )
        render :edit 
    
    end 

    def update
        @sub = Sub.find_by(id: params[:id])
        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash.now[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    private 
    def sub_params 
        params.require(:sub).permit(:title, :description)
    end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new 
        @user = User.new 
        render :new 
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            log_in!(@user)
            redirect_to user_url(@user)
        else 
            flash.now[:error] = @user.errors.full_messages
            render :new
        end
    end

    def index
        debugger
        @users = User.all 
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if flash[:errors] %>
      <p> <%= flash[:errors].join(",") %> </p>
  <% end %>
  <% if logged_in? %>
    <form action="<%= session_url %>" method="POST">
      <input type= "hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Log out">
    </form>
  <% end %>
  <body>
    <%= yield %>
  </body>
</html>

RedditClone/app/views/posts/edit.html.erb
<h1> Edit a Post </h1> 
<form action="<%= post_url(@post) %>" method="POST">
<input type="hidden" name="_method" value="PATCH">
<input type = "hidden" name = "authenticity_token" value = "<%=form_authenticity_token%>">
<label>Title 
<input type="text" name="post[title]" value="<%= @post.title %>">
</label>
<br>
<label>Content
<input type="text" name="post[content]" value="<%= @post.content %>">
</label>
<br>
<label>URL
<input type="text" name="post[url]" value="<%= @post.url %>">
</label>
<br>

<input type="submit" value="Edit a Post">
<form>

RedditClone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h2> Content </h2>
<p> <%= @post.content %> </p>


<a href="<%= @post.url %>"> <%= @post.url %> </a>

<% @post.crossposts.each do |crosspost| %>
    <p> Subreddit: <%= crosspost.sub.title %> </p>
<% end %>

<form action = "<%= edit_post_url(@post)%>" method = "POST">
<input type = "hidden" name = "_method" value = "GET">
<input type = "hidden" name = "authenticity_token" value = "<%= form_authenticity_token%>">

<button>Edit This Post</button>
</form>

RedditClone/app/views/subs/edit.html.erb
<h1> Edit Sub </h1>


<form action="<%= sub_url(@sub) %>" method="POST">
<input type = "hidden" name = "authenticity_token" value = "<%=form_authenticity_token%>">
<input type="hidden" name="_method" value="PATCH">
    <label> Title 
    <input type="text" name="sub[title]" value="<%=@sub.title%>" >
    <label>
    <label> Description
    <input type="text" name="sub[description]" value="<%=@sub.description%>" >
    <label>
    <input type="submit" value="Update Sub" >
</form>

RedditClone/app/views/subs/index.html.erb
<h1>All of the subs</h1>
<ul> 
<% @subs.each do |sub| %> 
    <li>
    <a href="<%= sub_url(sub) %>"> <%= sub.title %> </a>
    </li>
<% end %>

RedditClone/app/views/subs/new.html.erb
<h1> Create a sub </h1> 
<form action="<%= subs_url %>" method="POST">
<input type = "hidden" name = "authenticity_token" value = "<%=form_authenticity_token%>">
    <label> Title 
    <input type="text" name="sub[title]"  >
    <label>
    <label> Description
    <input type="text" name="sub[description]"  >
    <label>
    <input type="submit" value="Create Sub" >
</form>

RedditClone/app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<h2> <%= @sub.description %> </h2>

<h1> Add a Post </h1> 
<form action="<%= sub_posts_url(@sub) %>" method="POST">
<input type = "hidden" name = "authenticity_token" value = "<%=form_authenticity_token%>">
<label>Title 
<input type="text" name="post[title]">
</label>
<br>
<label>Content
<input type="text" name="post[content]">
</label>
<br>
<label>URL
<input type="text" name="post[url]">
</label>
<% @subs.each do |sub| %>
    <label><%= sub.title %>
    <input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>">
    </label> 
<% end %>

<br>
<input type= "submit" value="Create a Post">
<form>

<ul>
<% @sub.posts.each do |post| %>
    <a href="<%= post_url(post) %>"> <%= post.title %> </a> 
    <br>
<%end%>
</ul>



RedditClone/app/views/users/index.html.erb
<h1> User Index </h1>


<ul>
<% @users.each do |user| %>
    <a href="<%= user_url(user) %>"> <%= user.username %> </a>
    <br>
<% end %>
</ul>

RedditClone/app/views/users/new.html.erb
<h1> Sign Up </h1>

<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>" >
    <label> Username
    <input type="text" name="user[username]">
    </label>
    <label> Password
    <input type="password" name="user[password]">
    </label>
    <input type="submit" value="Sign Up" >
</form>

RedditClone/app/views/users/show.html.erb
<h1> User Show </h1>
<%= @user.username%>

<ul>
<% @user.subs.each do |sub| %>
    <li>
    <a href="<%= sub_url(sub) %>"> <%= sub.title %> </a>
    </li>
<% end %>
</ul>

<ul>
<% @user.posts.each do |post| %>
    <li>
    <a href="<%= post_url(post) %>"> <%= post.title %> </a>
    </li>
<% end %>
</ul>


<h1> Create a sub </h1> 
<form action="<%= subs_url %>" method="POST">
<input type = "hidden" name = "authenticity_token" value = "<%=form_authenticity_token%>">
    <label> Title 
    <input type="text" name="sub[title]"  >
    <label>
    <label> Description
    <input type="text" name="sub[description]"  >
    <label>
    <input type="submit" value="Create Sub" >
</form>